<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Title>Test Abstractions STA v3</Title>
		<IsPackable>true</IsPackable>
		<OutputType>Library</OutputType>

		<!-- NuGet Package Metadata -->
		<PackageId>ErikForwerk.TestAbstractions.STA.v3</PackageId>
		<Authors>Erik Forwerk</Authors>
		<Description>Test abstractions and helpers for unit testing with xUnit.v3 in STA (Single-Threaded Apartment) mode for Windows</Description>
		<PackageTags>testing;xunit;xunit.v3;abstractions;unittest;sta;windows</PackageTags>
		<RepositoryUrl>https://github.com/3rikF/test-abstractions</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Copyright>© 2026 Erik Forwerk</Copyright>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
		<PackageReference Include="xunit.v3.extensibility.core" Version="3.2.2" />
		<ProjectReference Include="..\ErikForwerk.TestAbstractions.v3\ErikForwerk.TestAbstractions.v3.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
</Project>
